import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useState } from 'react'
import axios from 'axios'

import LookupPostcode from '../components/LookupPostcode'
import SelectAddress from '../components/SelectAddress'
import { getPathFromElectionId } from '../lib/democracyClub/electionIdHelpers'
import { AddressData } from '../types'

export default function Home() {
  const STEP_LOOKUP_POSTCODE = 'LOOKUP_POSTCODE'
  const STEP_SELECT_ADDRESS = 'SELECT_ADDRESS'
  const STEP_FOUND_WARD = 'FOUND_WARD'
  const [step, setStep] = useState(STEP_LOOKUP_POSTCODE)

  const [loading, setLoading] = useState(false)

  const DEFAULT_ERROR_MESSAGE = "Oops, something went wrong. Please try entering your postcode again."
  const [error, setError] = useState('')

  const [postcode, setPostcode] = useState('')
  const [addresses, setAddresses] = useState<Array<AddressData>>([])
  const [selectedAddress, setSelectedAddress] = useState('')

  const router = useRouter()

  const lookupAddress = () => {
    setLoading(true)
    setError('')

    axios.get('/api/postcodeLookup', {
      params: {
        postcode: postcode,
        addressSlug: selectedAddress,
      }
    }).then(function (response) {
      console.log("Success", response.data)

      if (response.data.addressPicker) {
        console.log("Got some addresses!", response.data.addresses)
        setAddresses(response.data.addresses)
        setStep(STEP_SELECT_ADDRESS)
      } else if (response.data.featuredBallot) {
        console.log("Found the ward & ballot!", response.data.featuredBallot)
        // Redirect to the council/ward page
        try {
          const path = getPathFromElectionId(response.data.featuredBallot.ballotPaperId)
          console.log(`Redirecting to ${path}`)
          router.push(path)
          // TODO: pass on otherBallots as a URL param so they can be shown as well as the local election?
        } catch (error) {
          console.log("Error", error)
          setError(DEFAULT_ERROR_MESSAGE)
          setStep(STEP_LOOKUP_POSTCODE)
        }
      } else {
        // Found the ward, but no featuredBallot
        console.log("Found the ward with no ballot!")
        setStep(STEP_FOUND_WARD)
      }
    }).catch(function(error) {
      console.log("ERROR", error)
      console.log("USER ERROR", error?.response?.data?.userError)
      const errorMessage = error?.response?.data?.userError || DEFAULT_ERROR_MESSAGE
      setError(errorMessage)
      setStep(STEP_LOOKUP_POSTCODE)
    }).finally(() => {
      setLoading(false)
    })
  }

  return (
    <>
      <Head>
        <title>Local Tactical Voting</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Local Tactical Voting</h1>

        {step === STEP_LOOKUP_POSTCODE && (
          <LookupPostcode
            postcode={postcode}
            setPostcode={setPostcode}
            loading={loading}
            error={error}
            onClick={lookupAddress}
          />
        )}

        {step === STEP_SELECT_ADDRESS && (
          <SelectAddress
            addresses={addresses}
            selectedAddress={selectedAddress}
            setSelectedAddress={setSelectedAddress}
            loading={loading}
            error={error}
            onClick={lookupAddress}
          />
        )}

        {step === STEP_FOUND_WARD && (
          <p>Looks like you don&apos;t have an upcoming election</p>
        )}
      </main>
    </>
  )
}
